# Generated by Django 3.1 on 2020-09-26 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academic_years',
            name='FromDate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='academic_years',
            name='ToDate',
            field=models.DateTimeField(),
        ),
    ]
