# Generated by Django 3.1 on 2020-09-28 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20200926_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academic_years',
            name='FromDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='academic_years',
            name='ToDate',
            field=models.DateField(),
        ),
    ]
